[0m09:54:31.516744 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002595BDD5F50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002595B735510>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002595B996C90>]}


============================== 09:54:31.524743 | d46a9a03-ce24-482c-a8ab-835934de3954 ==============================
[0m09:54:31.524743 [info ] [MainThread]: Running with dbt=1.5.0
[0m09:54:31.524743 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\HtetHtetEi\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m09:54:31.524743 [debug] [MainThread]: Starter project path: C:\Users\HtetHtetEi\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\include\starter_project
[0m09:56:15.748687 [info ] [MainThread]: Profile fivetran_dbt written to C:\Users\HtetHtetEi\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m09:56:15.748687 [info ] [MainThread]: 
Your new dbt project "fivetran_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m09:56:15.748687 [debug] [MainThread]: Command `dbt init` succeeded at 09:56:15.748687 after 104.34 seconds
[0m09:56:15.748687 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002595BD4D9D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000259554E9590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002595B720050>]}
[0m09:56:15.748687 [debug] [MainThread]: Flushing usage events
[0m10:27:08.995890 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000197469CEE10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019746761F50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019746C7C090>]}


============================== 10:27:09.011565 | d514ae6b-25ac-40c5-bbfb-a85ffc24b314 ==============================
[0m10:27:09.011565 [info ] [MainThread]: Running with dbt=1.5.0
[0m10:27:09.011565 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\HtetHtetEi\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m10:27:09.011565 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\HtetHtetEi\Documents\fivetran_dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:27:09.011565 [debug] [MainThread]: Command `dbt run` failed at 10:27:09.011565 after 0.04 seconds
[0m10:27:09.011565 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000197466EA410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019746E14E10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000197467622D0>]}
[0m10:27:09.011565 [debug] [MainThread]: Flushing usage events
[0m10:28:33.717434 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002542A536E10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002542A607210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002542A254190>]}


============================== 10:28:33.717434 | 5af3def4-a6a5-4df9-8a11-c87aa511ce64 ==============================
[0m10:28:33.717434 [info ] [MainThread]: Running with dbt=1.5.0
[0m10:28:33.717434 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\HtetHtetEi\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m10:28:33.717434 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\HtetHtetEi\Documents\fivetran_dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:28:33.717434 [debug] [MainThread]: Command `dbt run` failed at 10:28:33.717434 after 0.04 seconds
[0m10:28:33.717434 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002542A228F50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002542A97A3D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002542A753190>]}
[0m10:28:33.717434 [debug] [MainThread]: Flushing usage events
